import type { Metadata } from "next";
import { Merriweather_Sans, Modak } from "next/font/google";
import Layout from "@/components/Layout";
import "./globals.css";
import { Suspense } from "react";

const merriweather_sans = Merriweather_Sans({
  subsets: ["latin"],
  variable: "--font-merriweather",
});
const modak = Modak({
  subsets: ["latin"],
  variable: "--font-modak",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather_sans.variable} ${modak.variable}`}>
        <Suspense>
          <Layout>{children}</Layout>
        </Suspense>
      </body>
    </html>
  );
}
